compressionLevel: mixed

enableGlobalCache: true

gitHooksPath: .github/hooks

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-git-hooks.cjs
    spec: 'https://raw.githubusercontent.com/trufflehq/yarn-plugin-git-hooks/main/bundles/%40yarnpkg/plugin-git-hooks.js'

yarnPath: .yarn/releases/yarn-4.0.2.cjs
